#qcplotter----
#For datasets with *2* sample groups, this function plots RT-corrected EICs for mass features designated in MFs.  
#
#Inputs:
#1. a processed xcmsset object (xset, probably xset3)
#2. xset.filtered, generated by mfmaker
#3. MFs, a one-column data.frame containing groupnames
#4. Fraction: "HilicNeg", "HilicPos", "CyanoAq", "CyanoDCM"
#5. PDF_Title: "Put me in quotes"

#Outputs:
#1. a pdf file containing raw and corrected EICs for mass features designated in list, MF.

MFs<- MFs_9312high_short 
Fraction <- "CyanoDCM"
PDF_Title<- "MFs_9312_75MostDifferent_tiled"

eicplotter <- function(MFs, Fraction, PDF_Title, PPM=5){
  
  library(xcms)
  library(seqinr)
  
    #Fraction <- FractionList[j]
    print(Fraction)
    DataDIR <- as.character(Dirs[Fraction, "DataDIR"])
    ResultsDIR <- as.character(Dirs[Fraction, "ResultsDIR"])
    
    #load in data
    setwd(ResultsDIR)
    
    xset.filtered <- read.csv(paste(Fraction, "xset.filtered.csv", sep="."))
    load(paste(Fraction, "xset3.RData", sep="."))

    #MFs <- MFs[,2]
    MFs <- as.character(MFs) 
    
    setwd(DataDIR)
    AllFiles <- list.files( DataDIR, pattern=".mzXML", full.names=F, 
                            recursive = TRUE)
    AllSamples <- sub(".mzXML", "", AllFiles)
    
    
    #Specify blanks, samples and pooled samples.
    Samples <-AllSamples[grepl("Smp", AllSamples)]
    Blanks <- AllSamples[grepl("Blk", AllSamples)]
    Pooled <- AllSamples[grepl("Poo", AllSamples)]
    sampleidx <- c(Samples, Blanks)
    
    #Specify treatment groups within samples
    
    Treat1 <- Samples[grepl(as.character(Treat1ID), Samples)]
    Treat2 <- Samples[grepl(as.character(Treat2ID), Samples)]
    
    
    # This next step will take some time to process, so don't expect instant results.
    
    EIC.corrected <- list()
    #MFs should be as.character. fix if there is an error.
    print("Extracting EICs. This will take some time.")
    for (i in 1:length(MFs)){   
      EIC.corrected[[i]] <- getEIC(xset3, rt="corrected", groupidx=MFs[i])
    }
    
    save(EIC.corrected, file = paste(Fraction, "EIC.corrected.RData", sep="."))
    
    #Make a dataframe for appearance of the QC
    Colors <- rep("#FFFFFF00",length(AllSamples)) #White
    QCAppear <- data.frame(AllSamples, Colors)
    QCAppear$Colors <- as.character(QCAppear$Colors)
    QCAppear[grepl(Treat1ID , AllSamples) , "Colors" ]<- "#FF0000FF" #Red with Alpha = 1
    QCAppear[grepl(Treat2ID , AllSamples) , "Colors" ] <- "#0000FFFF" #Blue with Alpha = 1
    QCAppear[grepl("_blk_" , AllSamples, ignore.case = TRUE) , "Colors"] <- "#BEBEBEFF"
    MyColors <- QCAppear$Colors

    
    setwd(ResultsDIR)
    pdf(paste(Sys.Date(), PDF_Title, "pdf", sep = "."), 8.5,11)
    
    #par(mfrow=c(4,3), mar=c(3,3,3,0.5)) 
    par(mfrow=c(4,3), mar=c(3,3,3,0.5)) 
    for(i in 1:length(MFs)){
      plot(EIC.corrected[[i]], xset3, groupidx=1, sampleidx=sampleidx, rtrange=Params["RTPLOT", Fraction], col=MyColors, main=MFs[i], legtext = NULL)
      
      #mtext(paste(i, xset.filtered$MassFeature[xset.filtered$groupname == MFs[i]]), 
      #      side=3, line=-1, adj=0, padj=0, cex=0.8)
      mtext(
        paste("RT Corrected", i,
              xset.filtered$MassFeature[xset.filtered$groupname == MFs[i]]),
        side = 3,
        line = -1,
        adj = 0,
        padj = 0,
        cex = 0.8
      )
      mtext(
        paste(Treat2ID, collapse = ", "),
        side = 3,
        line = -2,
        adj = 0,
        padj = 0,
        cex = 0.5,
        col = "blue"
      )
      mtext(
        paste(Treat1ID, collapse = ", "),
        side = 3,
        line = -3,
        adj = 0,
        padj = 0,
        cex = 0.5,
        col = "red"
      )
      mtext(
        "Blanks",
        side = 3,
        line = -4,
        adj = 0,
        padj = 0,
        cex = 0.5,
        col = "#BEBEBE"
      )
      
     # plot(EIC.corrected[[i]], xset3, groupidx=1, sampleidx=sampleidx, rtrange=Params["RTPLOT", Fraction], col=MyColors, legtext = NULL)
    # mtext(paste("Corrected", i, 
    #           xset.filtered$MassFeature[xset.filtered$groupname == MFs[i]]),
     #       side=3, line=-1, adj=0, padj=0, cex=0.8)
      
    }
  
    dev.off()
    print(paste(Fraction, "pdf saved", sep=""))
  }
  

