#Example workflow

#Set filepaths----

mzxmlpath <- "~/Desktop/MetabolomicsProjects/XCMS/EddyQE_NoBins_XCMS"
functionpath <- "~/Desktop/MetabolomicsProjects/RScripts"
outputpath <- "~/Desktop/MetabolomicsProjects/XCMS/EddyQE141216"

#Set XCMS parameters----

SNthresh <- 10 #up from 4
Prefilter <- c(3, 10000) 
PPM <- 2.5 
PeakWidth <- c(5.9, 13.5)
MinFrac <- 0.2 #Set to zero since samples are binned.  Set to value if samples are all in one folder
BW <- 3 #Ignoring IPO's suggestions on this guy 
MzWid <- 0.00307 #between injection resolution
MAX <- 52.8
Missing <- 10 #Optomize these
Extra <- 10 #Optomize these
Minsamp <- 10
#GapInit <- 0.78
#GapExtend <- 2.688

extractiontype <- "Aq" #or "DCM"
pvalue <- 0.05
column <- "RP" #or "HILIC"

#Run XCMSfunction----

setwd(functionpath)
source("XCMS_function.R")
XCMSList <- xcmsfunction(sampleset, extractiontype)
xset3 <- XCMSList[[1]]
xset.allpeaks <- XCMSList[[2]]

MFList <- mfmaker_ANOVA(xset.allpeaks, extractiontype, pvalue)
MFs <- MFList$mfs
sig.groupnames <- MFList$sig
bottom.fifty <- MFList$b50
xset.filtered <- MFList$filtered

sampleset <- samplesetmaker(extractiontype)

qcplotter(xset3, sampleset, xset.filtered, MFs)



#Match Target Compounds-----
#these can be targeted compounds or standards.  Right now code is set up to accomodate RP or HILIC targetted compounds


setwd("~/Desktop/Google Drive/3. Ingalls Lab/Compound info")
source("TargetCompounds_function.R")
setwd(outputpath)
TCList <- mfmatch(X,Y=xset.allpeaks, column, 5,0.4)
Matches <- TCList$matches 
Target.Compound.Areas <- TCList$tca
Target.Compounds <- TCList$tcl



#Run Camera_Function----

setwd(functionpath)
source("Camera_Function_191216.R")
CAMERAlist <- camera (xset3, Polarity ="positive", PPM = 5)
xset.annot <- CAMERAlist[[1]]
xsaFA <- CAMERAlist[[2]]

#Run Camera post-processing----
#Calculate adducts and isotopes for mass features and calculate neutral mass for ions with two or more adducts
#Load in CAMERA xsAnnotate object and Peaklist

setwd(functionpath)
source("CAMERA_object_postprocessing_function.R")
IonList <- camerapostprocess(xsaFA, xset.annot)
OtherIons <- IonList[[3]]

#Neutral Mass List function----
#Compare mass feature priority lists generated by XCMS script (e.g. 50 most abundant compounds, compounds with p<0.05) to adduct list.  Dereplicate priority lists and output a list of neutral masses relevant to data set.  Option to output a list of "pseudo-neutral masses" calculated by subtracting an H+ from all mass features which have no associated adduct.

#Requires OtherIons, *.filtered peaklist from XCMS script, and sig.groupnames from XCMS script


setwd(functionpath)
source("NeutralMassList_function.R")
NMLists <- NMLfunction (OtherIons, xset.filtered, sig.groupnames)
UniqueNML <- NMLists[[1]]
UniqueHypNM <- NMLists[[3]]
setwd(outputpath)
write.csv(UniqueHypNM, file="HypNM_Export.csv")
write.csv(UniqueNML, file="NML_Export.csv")
