#Example workflow

#Set filepaths----

mzxmlpath <- "~/Desktop/MetabolomicsProjects/XCMS/EddyQE_NoBins_XCMS" #raw data path
functionpath <- "~/Desktop/MetabolomicsProjects/RScripts" #location of scripts
outputpath <- "~/Desktop/MetabolomicsProjects/XCMS/EddyQE141216" #path that files are written to 
targetcompoundpath <- "~/Desktop/Google Drive/3. Ingalls Lab/Compound info" #this is where MRM_Methods_Table.csv is stored
  
#Set XCMS parameters----

SNthresh <- 10 #up from 4
Prefilter <- c(3, 10000) 
PPM <- 2.5 
PeakWidth <- c(5.9, 13.5)
MinFrac <- 0.2 #Set to zero since samples are binned.  Set to value if samples are all in one folder
BW <- 3 #Ignoring IPO's suggestions on this guy 
MzWid <- 0.00307 #between injection resolution
MAX <- 52.8
Missing <- 12 # the number of missing samples to allow in RT correction groups
Extra <- 10 #Optomize these
Minsamp <- 3 #the minimum # of samples required to have that mass feature
#GapInit <- 0.78
#GapExtend <- 2.688

extractiontype <- "Aq" #or "DCM"
pvalue <- 0.05
column <- "RP" #or "HILIC"
excludedsamples <- "DSS3|SA11" #xcmsfunction and samplesetmaker
includedsamples <- "SWT|Glu|groupname" #argument to mfmaker

#Build sampleset----

sampleset <- samplesetmaker(extractiontype, excludedsamples)

#Run XCMSfunction----

setwd(functionpath)
source("XCMS.function.R")
XCMSList <- xcmsfunction(sampleset, extractiontype, excludedsamples)
xset3 <- XCMSList[[1]]
xset.allpeaks <- XCMSList[[2]]

#*******THIS FUNCTION MUST BE CUSTOMIZED FOR EACH DATA SET!!!!!!!******
setwd(functionpath)
source("mfmakerANOVA_VibrioEdition.function.R")
MFList <- mfmaker_ANOVA(xset.allpeaks, extractiontype, pvalue, includedsamples)
MFs <- MFList$mfs
sig.groupnames <- MFList$sig
bottom.fifty <- MFList$b50
xset.filtered <- MFList$filtered

qcplotter(xset3, sampleset, xset.filtered, MFs)



#Match Target Compounds-----
#these can be targeted compounds or standards.  Right now code is set up to accomodate RP or HILIC targetted compounds


setwd(functionpath)
source("TargetCompounds.function.R")
setwd(outputpath)
TCList <- mfmatch(X,Y=xset.allpeaks, column, 5,0.4)
Matches <- TCList$matches 
Target.Compound.Areas <- TCList$tca
Target.Compounds <- TCList$tcl
write.csv(Target.Compound.Areas, file=paste(extractiontype,"TargetCompounds.csv", sep="."))


#Run Camera_Function----
#Calculate adducts and isotopes for mass features and calculate neutral mass for ions with two or more adducts
#
setwd(functionpath)
source("CAMERA.function.R")
CAMERAlist <- camera (xset3, Polarity ="positive", PPM = 5)
xset.annot <- CAMERAlist[[1]]
xsaFA <- CAMERAlist[[2]]
setwd(functionpath)
save(CAMERAlist, file=paste(extractiontype, "CAMERAlist.RData", sep="."))

#Run Camera post-processing----
#Load in CAMERA xsAnnotate object and Peaklist

setwd(functionpath)
source("CAMERApostprocessing.function.R")
IonList <- camerapostprocess(xsaFA, xset.annot)
OtherIons <- IonList[[3]]
setwd(functionpath)
write.csv(OtherIons, file=paste(extractiontype, "OtherIons.csv", sep="."))

#Neutral Mass List function----
#Compare mass feature priority lists generated by XCMS script (e.g. 50 most abundant compounds, compounds with p<0.05) to adduct list.  Dereplicate priority lists and output a list of neutral masses relevant to data set.  Option to output a list of "pseudo-neutral masses" calculated by subtracting an H+ from all mass features which have no associated adduct.

#Requires OtherIons, *.filtered peaklist from XCMS script, and sig.groupnames from XCMS script


setwd(functionpath)
source("NeutralMassList.function.R")
NMLists <- NMLfunction (OtherIons, xset.filtered, sig.groupnames)
UniqueNML <- NMLists[[1]]
UniqueHypNM <- NMLists[[3]]
NeutralMassList <- NMLists[[4]]
setwd(outputpath)
write.csv(NeutralMassList, file=paste(extractiontype, "NeutralMassList.csv", sep="."))
write.csv(UniqueHypNM, file="HypNM_Export.csv")
write.csv(UniqueNML, file="NML_Export.csv")
