---
title: "Example_workflow.V2"
author: "Laura Hmelo"
date: "January 27, 2017"
output:
---

#This workflow begins to merge features of KHeal's XCMS scritps and functions.

#Set filepaths
```{r Set filepaths}

ExpDIR <- "~/Desktop/MetabolomicsProjects/Vesicles_January_2017" #raw data path
functionDIR <- "~/Desktop/MetabolomicsProjects/RScripts" #location of scripts
#outputpath <- "~/Desktop/MetabolomicsProjects/XCMS/EddyQE141216" #path that files are written to 
targetcompoundpath <- "~/Desktop/Google Drive/3. Ingalls Lab/Compound info" #this is where MRM_Methods_Table.csv is stored
```

#Set parameters
```{r Set parameters and define groups}
#Experiment <- "Vesicles_January_2017"
setwd(ExpDIR)
Params <- read.csv("Params.csv",  row.names=1)

FractionList <- c("HILICNeg", "HILICPos", "CyanoAq", "CyanoDCM")

#extractiontype <- "Aq" #or "DCM"
pvalue <- 0.05
column <- "RP" #or "HILIC"
#excludedsamples <- "DSS3|SA11" #xcmsfunction and samplesetmaker
#includedsamples <- "9313|9312|groupname" #argument to mfmaker

#Pick 2 IDs that will work to call Biological replicates to compared for the QC step
Treat1ID <- "9313"
Treat2ID <- "9312"
```


```{r Set your Directories}
#ExpDIR <-paste(basepath, Experiment, sep = "/", collapse = NULL)
FractionDIR <- c()
ResultsDIR <- c()
DataDIR <- c()
for (j in 1:length(FractionList)){
  FractionDIR[j] <- paste(ExpDIR, "/", FractionList[j], sep = "", collapse = NULL)
  ResultsDIR[j] <- paste(FractionDIR[j], "/Results", Sys.Date(), sep = "", collapse = NULL)
 dir.create(file.path(ResultsDIR[j])) #, showWarnings = FALSE) #Comment out if you don't need to make the folder i.e. you've already run XCMS and need to redo the next steps
  DataDIR <-  paste(FractionDIR, "/rawdat", sep = "", collapse = NULL)
  }
Dirs <- data.frame(FractionList, FractionDIR, ResultsDIR, DataDIR)
#Dirs <- Dirs %>% mutate(ResultsDIR = ResultsDIR %>%  str_replace("2017-01-24","2017-01-22") ) #If you are accessing results made on previous days, use this bit of code (^) to redirect to older results
rownames(Dirs) <- Dirs$FractionList
```

#Run XCMSfunction

```{r Run XCMSfunction on all fractions specified in FractionList}
setwd(functionDIR)
source("XCMS.V2.function.R")

#run XCMS
xcmsfunction()
#XCMSList <- xcmsfunction(DatFiles)
#xset3 <- XCMSList[[1]]
#xset.allpeaks <- XCMSList[[2]]

```

#*******THIS FUNCTION MUST BE CUSTOMIZED FOR EACH DATA SET!!!!!!!******

```{r}
setwd(functionDIR)
source("mfmakerANOVA_Vesicles.function.R")
MFList <- mfmaker_ANOVA(xset.allpeaks, extractiontype, pvalue, includedsamples)
MFs <- MFList$mfs
sig.groupnames <- MFList$sig
bottom.fifty <- MFList$b50
xset.filtered <- MFList$filtered

setwd(functionDIR)
source("qcplotter.V2.function.R")
qcplotter()

```

#Dereplication of XCMS output
```{r Dereplicate XCMS output}
#these can be targeted compounds or standards.  Right now code is set up to accomodate RP or HILIC targetted compounds


setwd(functionDIR)
source("TargetCompounds.function.R")
setwd(outputpath)
TCList <- mfmatch(X,Y=xset.allpeaks, column, 5,0.4)
Matches <- TCList$matches 
Target.Compound.Areas <- TCList$tca
Target.Compounds <- TCList$tcl
write.csv(Target.Compound.Areas, file=paste(extractiontype,"TargetCompounds.csv", sep="."))
```

#Run Camera_Function
```{r Run CAMERA}
#Calculate adducts and isotopes for mass features and calculate neutral mass for ions with two or more adducts
#
setwd(functionDIR)
source("CAMERA.V2.function.R")
CAMERAlist <- camera (PPM = 5)
#xset.annot <- CAMERAlist[[1]]
#xsaFA <- CAMERAlist[[2]]
#setwd(functionDIR)
#save(CAMERAlist, file=paste(extractiontype, "CAMERAlist.RData", sep="."))
```

#Run Camera post-processing
#Load in CAMERA xsAnnotate object and Peaklist

```{r Run all CAMERA post-processing}
setwd(functionDIR)
source("CAMERApostprocessing.function.R")
IonList <- camerapostprocess(xsaFA, xset.annot)
OtherIons <- IonList[[3]]
setwd(functionDIR)
write.csv(OtherIons, file=paste(extractiontype, "OtherIons.csv", sep="."))

#Neutral Mass List function
#Compare mass feature priority lists generated by XCMS script (e.g. 50 most abundant compounds, compounds with p<0.05) to adduct list.  Dereplicate priority lists and output a list of neutral masses relevant to data set.  Option to output a list of "pseudo-neutral masses" calculated by subtracting an H+ from all mass features which have no associated adduct.

#Requires OtherIons, *.filtered peaklist from XCMS script, and sig.groupnames from XCMS script


setwd(functionDIR)
source("NeutralMassList.function.R")
NMLists <- NMLfunction (OtherIons, xset.filtered, sig.groupnames)
UniqueNML <- NMLists[[1]]
UniqueHypNM <- NMLists[[3]]
NeutralMassList <- NMLists[[4]]
setwd(outputpath)
write.csv(NeutralMassList, file=paste(extractiontype, "NeutralMassList.csv", sep="."))
write.csv(UniqueHypNM, file="HypNM_Export.csv")
write.csv(UniqueNML, file="NML_Export.csv")
```
