#qcplotter----
#This function plots EICs for mass features designated in MFs.  
#
#Inputs:
#1. a processed xcmsset object (xset, probably xset3)
#2. xset.filtered, generated by mfmaker
#3. MFs, generated by mfmaker
#4. sampleset, generated by function samplesetmaker
#
#Outputs:
#1. a pdf file containing raw and corrected EICs for mass features designated in list, MF.



qcplotter <- function(PPM=5){
  
  library(xcms)
  library(seqinr)
  
  for (j in 1:length(FractionList)){
    Fraction <- FractionList[j]
    print(Fraction)
    DataDIR <- as.character(Dirs[Fraction, "DataDIR"])
    ResultsDIR <- as.character(Dirs[Fraction, "ResultsDIR"])
    
    #load in data
    setwd(ResultsDIR)
    
    xset.filtered <- read.csv(paste(Fraction, "xset.filtered.csv", sep="."))
    load(paste(Fraction, "xset3.RData", sep="."))
    MFs <- read.csv(paste(Fraction, "MFs.csv", sep="."))
    MFs <- MFs[,2]
    MFs <- as.character(MFs) 
    
    setwd(DataDIR)
    AllFiles <- list.files( DataDIR, pattern=".mzXML", full.names=F, 
                            recursive = TRUE)
    AllSamples <- sub(".mzXML", "", AllFiles)
    
    
    #Specify blanks, samples and pooled samples.
    Samples <-AllSamples[grepl("Smp", AllSamples)]
    Blanks <- AllSamples[grepl("Blk", AllSamples)]
    Pooled <- AllSamples[grepl("Poo", AllSamples)]
    
    #Specify treatment groups within samples
    
    Treat1 <- Samples[grepl(as.character(Treat1ID), Samples)]
    Treat2 <- Samples[grepl(as.character(Treat2ID), Samples)]
    
    
    # This next step will take some time to process, so don't expect instant results.
    
    EIC.uncorrected <- list()
    EIC.corrected <- list()
    #MFs should be as.character. fix if there is an error.
    print("Extracting EICs. This will take some time.")
    for (i in 1:length(MFs)){   
      EIC.uncorrected[[i]] <- getEIC(xset3, rt="raw", groupidx=MFs[i])
      EIC.corrected[[i]] <- getEIC(xset3, rt="corrected", groupidx=MFs[i])
    }
    
    #Make a dataframe for appearance of the QC
    Colors <- rep("#FFFFFF00",length(AllSamples)) #White
    QCAppear <- data.frame(AllSamples, Colors)
    QCAppear$Colors <- as.character(QCAppear$Colors)
    QCAppear[grepl(Treat1ID , AllSamples) , "Colors" ]<- "#FF0000FF" #Red with Alpha = 1
    QCAppear[grepl(Treat2ID , AllSamples) , "Colors" ] <- "#0000FFFF" #Blue with Alpha = 1
    QCAppear[grepl("_blk_" , AllSamples, ignore.case = TRUE) , "Colors"] <- "#BEBEBEFF"
    MyColors <- QCAppear$Colors
    
    
    #ColRainbow <- colorRampPalette(c("green", "blue", "purple")) 
    #MyColors <- c(ColRainbow(RandSamp-1), "red")
    
    setwd(DataDIR)
    
    #
    RandSamp <- round(runif(1, min = 1, max = length(Samples)))
    LastSamp <- Samples[RandSamp[length(RandSamp)]]
    
    xset.raw <- xcmsRaw(paste(LastSamp, ".mzXML", sep = ""), profstep=0.01, profmethod="bin")
    
    
    setwd(ResultsDIR)
    pdf(paste(Sys.Date(), Fraction, "xset_QC.pdf", sep = "."), 8.5,11)
    
    par(mfrow=c(4,3), mar=c(3,3,3,0.5)) 
    for(i in 1:length(MFs)){
      plot(EIC.uncorrected[[i]], xset3, groupidx=1, rtrange=Params["RTPLOT", Fraction], col=MyColors, main=MFs[i], legtext = NULL)
      
      #mtext(paste(i, xset.filtered$MassFeature[xset.filtered$groupname == MFs[i]]), 
      #      side=3, line=-1, adj=0, padj=0, cex=0.8)
      mtext(
        paste("Uncorrected", i,
              xset.filtered$MassFeature[xset.filtered$groupname == MFs[i]]),
        side = 3,
        line = -1,
        adj = 0,
        padj = 0,
        cex = 0.8
      )
      mtext(
        paste(Treat2ID, collapse = ", "),
        side = 3,
        line = -2,
        adj = 0,
        padj = 0,
        cex = 0.5,
        col = "blue"
      )
      mtext(
        paste(Treat1ID, collapse = ", "),
        side = 3,
        line = -3,
        adj = 0,
        padj = 0,
        cex = 0.5,
        col = "red"
      )
      mtext(
        "Blanks",
        side = 3,
        line = -4,
        adj = 0,
        padj = 0,
        cex = 0.5,
        col = "#BEBEBE"
      )
      
      plot(EIC.corrected[[i]], xset3, groupidx=1, rtrange=Params["RTPLOT", Fraction], col=MyColors)
      mtext(paste("Corrected", i, 
                  xset.filtered$MassFeature[xset.filtered$groupname == MFs[i]]),
            side=3, line=-1, adj=0, padj=0, cex=0.8)
      
  
      RT <- xset.filtered$rt[xset.filtered$groupname == MFs[i]] 
      RTRange <- c(RT-30, RT+30)
      mz <- xset.filtered$mz[xset.filtered$groupname == MFs[i]] 
      mzRange <- c(mz-0.02, mz+0.02)
      mzRange.poly.low <- mz- mz*(0.5*PPM)/1e6
      mzRange.poly.up <- mz*(0.5*PPM)/1e6 + mz
      
      
      plotRaw(xset.raw, mzrange=mzRange, rtrange=RTRange, log=FALSE) 
      abline(h=mz, lty=2, col="gray35")
      #mtext(paste("abund =", round(xset.filtered[
      # xset.filtered$groupname == MFs[i]])), 
      #SampCol[RandSamp[length(RandSamp)]]], digits=0)), 
      #   side=3, line=-1, adj=0, padj=0, cex=0.8)
      polygon(c(RTRange[2], RTRange[1], RTRange[1], RTRange[2]), 
              c(mzRange.poly.up, mzRange.poly.up,
                mzRange.poly.low, mzRange.poly.low), 
              col=col2alpha("blue", alpha=0.1), border=NA)
      abline(v=RT, lty=2, col="gray35")
    }
  
    dev.off()
    print(paste(Fraction, "pdf saved", sep=""))
  }
  
}
